name: clean

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * SAT"

jobs:
  clean:
    runs-on: ubuntu-latest
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      NOTION_TASKS_DATABASE_ID: ${{ secrets.NOTION_TASKS_DATABASE_ID }}
      NOTION_PROJECTS_DATABASE_ID: ${{ secrets.NOTION_PROJECTS_DATABASE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Week
        id: check_week
        run: python scripts/check_cleaning_week.py
        continue-on-error: true

      - name: Run Clean Room
        if: ${{ steps.check_week.outcome == 'success' }}
        run: |
          python scripts/add_task.py \
            --name "Clean room" \
            --status "On Deck" \
            --project House \
            --task-type "work"
      
      - name: Run Drain Water Heater
        if: ${{ steps.check_week.outcome == 'success' }}
        run: |
          python scripts/add_task.py \
            --name "Drain water heater for 10 minutes" \
            --status "On Deck" \
            --project House \
            --task-type work
