name: weekly_tuesday

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * TUE" # midnight cdt

jobs:
  weekly_tuesday_stuff:
    runs-on: ubuntu-latest
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      NOTION_TASKS_DATABASE_ID: ${{ secrets.NOTION_TASKS_DATABASE_ID }}
      NOTION_PROJECTS_DATABASE_ID: ${{ secrets.NOTION_PROJECTS_DATABASE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: GARBAGE DAY!!!
        run: |
          python scripts/add_task.py \
            --name "Take out the trash" \
            --project House \
            --status "On Deck" \
            --task-type "work" \
            --skip-existing

      - name: Pay Bills
        run: |
          python scripts/add_task.py \
            --name "Pay bills" \
            --project House \
            --status "On Deck" \
            --task-type "work" \
            --skip-existing

      - name: Check Week
        id: check_week
        run: |
          python scripts/check_recycling_week.py
        continue-on-error: true

      - name: Recycling
        if: ${{ steps.check_week.outcome == 'success' }}
        run: |
          python scripts/add_task.py \
            --name "Recycling" \
            --project House \
            --status "On Deck" \
            --task-type "work" \
            --skip-existing
